name: ✨ Feature request
description: Suggest an idea for this project
body:
  - type: dropdown
    attributes:
      label: Type of feature
      description: Select the type of feature request.
      multiple: false
      options:
        - "New feature"
        - "Documentation"
        - "Style and UI"
        - "Code refactor"
        - "Performance improvements"
        - "New test"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Give us a brief description of the feature or enhancement you would like
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context about the feature here.
        You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
